import React, { useState, useRef } from 'react';
import {
    Upload, Sparkles, Copy, Check, Info, Tag, Wrench, Share2, Zap, Heart, List, Maximize, Image as ImageIcon, Edit3, Save
} from 'lucide-react';
import { generateContent } from './aiService';
import { parseApiError } from './utils/errorParser';

export default function ProductLabelPromptTool({ onTaskComplete }) {
    // — Form State —
    const [images, setImages]           = useState([]);
    const [productName, setProductName] = useState('');
    const [ingredients, setIngredients] = useState('');
    const [benefits, setBenefits]       = useState('');
    const [dimensions, setDimensions]   = useState('');

    // — Generation State —
    const [isGenerating, setIsGenerating] = useState(false);
    const [currentStep, setCurrentStep]   = useState('idle'); // 'idle' | 'loading' | 'success'
    const [countdown, setCountdown]       = useState(30);

    // — Result State —
    const [designPrompt, setDesignPrompt]     = useState('');
    const [arabicAnalysis, setArabicAnalysis] = useState('');

    // — Edit Toggle State —
    const [isEditing, setIsEditing]         = useState(false);
    const [editedAnalysis, setEditedAnalysis] = useState('');

    // — Copy State —
    const [copiedDesign, setCopiedDesign]     = useState(false);
    const [copiedAnalysis, setCopiedAnalysis] = useState(false);

    const [error, setError] = useState('');
    const fileRef = useRef(null);

    // ─── File Handler ───────────────────────────────────────────────────────────
    const handleFiles = async (e) => {
        const files = Array.from(e.target.files || []);
        if (!files.length) return;
        const slots = 1 - images.length;
        const b64s = await Promise.all(
            files.slice(0, slots).map(f => new Promise(res => {
                const r = new FileReader();
                r.onloadend = () => res(r.result);
                r.readAsDataURL(f);
            }))
        );
        setImages(prev => [...prev, ...b64s].slice(0, 1));
        e.target.value = '';
    };

    const removeImg = i => setImages(prev => prev.filter((_, idx) => idx !== i));

    // ─── AI System Prompt ────────────────────────────────────────────────────────
    const exactPromptText = `Act as a world-class Product Packaging Designer, Vision AI Expert, and Prompt Engineer specializing in e-commerce product labels generated by 'Nano Banana Pro'.

You will receive an uploaded image of a product or label, along with optional user inputs: [Product Name], [Ingredients], [Benefits/Usage], and [Dimensions].

### YOUR MISSION HAS TWO CRITICAL STEPS:

### STEP 1: DEEP IMAGE ANALYSIS & DATA FILL-IN (ARABIC)
Deeply analyze the uploaded image. Read any visible text (OCR), identify the product niche, the visual elements, and the target audience. 

Evaluate the provided user inputs. For ANY missing or empty input, you MUST generate highly professional Arabic content based on your image analysis:
- Missing [Product Name]? Extract it from the image or invent a strong, relevant Arabic brand name.
- Missing [Ingredients]? Deduce logical, scientifically plausible ingredients based on the product type and translate them to Arabic.
- Missing [Benefits/Usage]? Write professional Arabic usage instructions and key benefits.
- Missing [Dimensions]? Analyze the physical shape of the packaging (e.g., cylindrical bottle, box). Deduce the optimal Aspect Ratio for a flat label. Choose from standard generation ratios only (e.g., "21:9" or "16:9" for wrap-around, "3:4" for front-box).

Present this finalized, organized Arabic data clearly in your response so I can review it before the image prompt.

### STEP 2: NANO BANANA PRO DESIGN PROMPT
After presenting the finalized data, output a single, consolidated READY-TO-COPY design prompt for the "Nano Banana Pro" image generator.

---
### CRITICAL INSTRUCTIONS FOR STEP 2 OUTPUT:
1. Output Format: Provide the entire design prompt inside a single code block.
2. Layout Context: Describe the image as a "flat, unwrapped label layout". If the ratio is wide (e.g. 21:9), state it's divided into 3 vertical columns.
3. Typography Integration: You MUST take the Arabic text finalized in STEP 1, and insert it directly into the Step 2 prompt replacing the placeholders. 
4. The Arabic text must be placed EXACTLY inside quotation marks " ".
5. DO NOT render any English structural labels inside the final prompt. Just the visual descriptions and the Arabic text in quotes.

--- USE THIS EXACT TEMPLATE FOR STEP 2 (DESIGN PROMPT) ---

Act as a world-class Product Packaging Designer. Generate a high-resolution, pure digital graphic design of a FLAT, UNWRAPPED product label (Aspect Ratio [Insert Final Dimensions from Step 1]) for [Describe the product visually based on the image analysis].

CRITICAL FORMAT RULE: This is a flat label design. Divide the layout distinctly. No 3D mockups, just the flat printable label.

AESTHETIC & FLOW INSTRUCTIONS:
Background: Clean, premium aesthetic with [insert 2 color palette based on product image]. Add subtle vertical divider lines to separate the panels clearly. Maintain AMPLE NEGATIVE SPACE around all text blocks to prevent clutter.

* LEFT SECTION (Usage & Safety): Clean layout aligned to the left. Small minimalist line-art icons.
* Small, Crisp Blue Text: "[Insert Final Arabic Directions/Usage from Step 1]"
* Small, Crisp Dark Text: "[Insert Final Arabic Warnings/Precautions from Step 1]"
* Graphic element: A row of 4 very small, high-quality certification vector icons (like ISO, GMP, Organic) at the bottom.

* CENTER SECTION (Main Branding): The Hero section. Center-aligned with generous margins.
* Graphic element (Top Center): A dynamic, highly detailed vector illustration of [Describe a relevant graphic derived from the image analysis].
* HUGE BOLD STYLIZED TEXT: "[Insert Final Arabic Product Name from Step 1]"
* Large Bold Text: "[Insert Final Arabic Main Benefit from Step 1]"
* Small Bottom Text inside a pill-shaped graphic: "60 كبسولة / 60 Capsules"

* RIGHT SECTION (Ingredients & Info): Clean structured layout aligned to the right. 
* Medium BOLD TEXT: "المكونات / INGREDIENTS"
* Small, Crisp Text formatted as a highly minimalist nutritional table with very thin, subtle lines: "[Insert Final Arabic Ingredients list from Step 1]"
* Small Text (Bottom Right): "صنع خصيصاً لعملائنا | جودة مضمونة"

Final Polish: Ensure the overall look is ultra-professional, ready-to-print vector style, with crisp typography graphics and a balanced, uncluttered layout.`;

    // ─── Generate Handler ────────────────────────────────────────────────────────
    const handleGenerate = async () => {
        if (!images.length) { setError('يرجى رفع صورة المنتج أولاً.'); return; }
        setError('');
        setDesignPrompt('');
        setArabicAnalysis('');
        setEditedAnalysis('');
        setIsEditing(false);
        setIsGenerating(true);
        setCurrentStep('loading');
        setCountdown(30);

        const startTime = Date.now();
        const timer = setInterval(() => {
            setCountdown(prev => (prev <= 1 ? 0 : prev - 1));
        }, 1000);

        const userContext = `
Provided User Inputs:
[Product Name]: ${productName.trim() || 'Missing'}
[Ingredients]: ${ingredients.trim() || 'Missing'}
[Benefits/Usage]: ${benefits.trim() || 'Missing'}
[Dimensions]: ${dimensions || 'Missing'}
        `.trim();

        try {
            const outputText = await generateContent({
                systemPrompt: exactPromptText,
                userPrompt: userContext,
                imageBase64: images[0]
            });

            // Split: code block → designPrompt, everything before → arabicAnalysis
            const promptRegex = /```(?:[\w\s]*)\n([\s\S]*?)```/i;
            const promptMatch = outputText.match(promptRegex);

            let extractedPrompt   = '';
            let extractedAnalysis = '';

            if (promptMatch) {
                extractedPrompt   = promptMatch[1].trim();
                extractedAnalysis = outputText.substring(0, promptMatch.index).trim();
            } else {
                extractedPrompt   = outputText.trim();
                extractedAnalysis = 'ملاحظة: الذكاء الاصطناعي لم يقم بفصل المخرجات بشكل صحيح.';
            }

            setDesignPrompt(extractedPrompt);
            setArabicAnalysis(extractedAnalysis);
            setEditedAnalysis(extractedAnalysis);

            const elapsed   = Date.now() - startTime;
            const remaining = Math.max(0, 30000 - elapsed);
            if (remaining > 0) await new Promise(res => setTimeout(res, remaining));

            setCurrentStep('success');
            if (onTaskComplete) onTaskComplete();
            setTimeout(() => document.getElementById('label-prompt-result')?.scrollIntoView({ behavior: 'smooth' }), 200);
        } catch (err) {
            const userFriendlyMsg = parseApiError(err);
            setError(userFriendlyMsg);
            setCurrentStep('idle');
        } finally {
            setIsGenerating(false);
            clearInterval(timer);
        }
    };

    // ─── Copy Handlers ───────────────────────────────────────────────────────────
    const handleCopyDesign = () => {
        if (!designPrompt) return;
        navigator.clipboard.writeText(designPrompt);
        setCopiedDesign(true);
        setTimeout(() => setCopiedDesign(false), 2000);
    };

    const handleCopyAnalysis = () => {
        const text = isEditing ? editedAnalysis : arabicAnalysis;
        if (!text) return;
        navigator.clipboard.writeText(text);
        setCopiedAnalysis(true);
        setTimeout(() => setCopiedAnalysis(false), 2000);
    };

    // ─── Edit / Save Handlers ────────────────────────────────────────────────────
    const handleEdit = () => {
        setEditedAnalysis(arabicAnalysis);
        setIsEditing(true);
    };

    const handleSave = () => {
        setArabicAnalysis(editedAnalysis);
        setIsEditing(false);
    };

    // ─── Reset ───────────────────────────────────────────────────────────────────
    const handleReset = () => {
        setImages([]);
        setProductName('');
        setIngredients('');
        setBenefits('');
        setDimensions('');
        setDesignPrompt('');
        setArabicAnalysis('');
        setEditedAnalysis('');
        setIsEditing(false);
        setCopiedDesign(false);
        setCopiedAnalysis(false);
        setError('');
        if (fileRef.current) fileRef.current.value = '';
    };

    // ─── Style Helpers ───────────────────────────────────────────────────────────
    const card = 'bg-slate-900/70 border border-white/10 rounded-3xl p-7 backdrop-blur-sm';
    const lbl  = 'flex items-center gap-2 text-xs font-bold text-white/60 mb-2';
    const inp  = 'w-full bg-slate-950 border border-white/10 rounded-xl p-3 text-white text-sm outline-none focus:border-pink-500 transition-all placeholder:text-white/20';

    // ─── Render ──────────────────────────────────────────────────────────────────
    return (
        <div className="h-full overflow-y-auto text-slate-100" dir="rtl" style={{ scrollbarWidth: 'none' }}>
            <div className="max-w-7xl mx-auto px-6 md:px-10 py-10">

                {/* ── Header ── */}
                <div className="text-center mb-12">
                    <div className="inline-flex items-center gap-2 bg-pink-500/10 border border-pink-500/20 text-pink-400 text-xs font-bold px-4 py-1.5 rounded-full mb-5">
                        <Share2 size={13} /> Nano Banana Pro
                    </div>
                    <h1 className="text-4xl md:text-5xl font-black mb-3 leading-tight">
                        برومبت ملصقات المنتجات
                        <span className="block text-transparent bg-clip-text bg-gradient-to-r from-pink-400 to-rose-400 text-2xl md:text-3xl mt-2">
                            تصميم لأغلفة المنتجات (Packaging) باحترافية
                        </span>
                    </h1>
                    <p className="text-white/40 text-sm max-w-lg mx-auto leading-relaxed">
                        قم برفع صورة المنتج ودع الذكاء الاصطناعي يحلل لك أفضل المكونات والفوائد ويولد لك برومبت جاهز للنسخ في Nano Banana Pro.
                    </p>
                </div>

                {/* ── Error Banner ── */}
                {error && (
                    <div className="mb-6 bg-red-500/10 border border-red-500/30 text-red-400 px-5 py-3 rounded-2xl text-sm">⚠️ {error}</div>
                )}

                {/* ── Input Form ── */}
                <div className="max-w-4xl mx-auto space-y-6">
                    <div className={card + ' space-y-7'}>

                        {/* Image Uploader */}
                        <div>
                            <p className={lbl}><ImageIcon size={13} className="text-pink-400" />صورة المنتج/الغلاف (مطلوبة)</p>
                            <div
                                onClick={() => images.length < 1 && fileRef.current?.click()}
                                className={`border-2 border-dashed rounded-2xl p-5 cursor-pointer transition-all flex flex-col items-center justify-center min-h-[180px]
                                    ${images.length ? 'border-pink-500/40 bg-pink-500/5' : 'border-white/10 hover:border-pink-500/40 bg-white/5'}
                                    ${images.length >= 1 ? 'opacity-50 cursor-not-allowed' : ''}`}
                            >
                                <input type="file" ref={fileRef} onChange={handleFiles} accept="image/*" className="hidden" />
                                {images.length ? (
                                    <div className="relative aspect-video w-full max-w-sm mx-auto">
                                        <img src={images[0]} className="w-full h-full object-cover rounded-xl border border-white/10" alt="product" />
                                        <button
                                            onClick={e => { e.stopPropagation(); removeImg(0); }}
                                            className="absolute -top-2 -right-2 bg-red-500 text-white w-6 h-6 rounded-full text-xs flex items-center justify-center z-10"
                                        >✕</button>
                                    </div>
                                ) : (
                                    <>
                                        <div className="w-14 h-14 bg-pink-500/15 rounded-full flex items-center justify-center mb-3">
                                            <Upload size={26} className="text-pink-400" />
                                        </div>
                                        <p className="font-bold text-base mb-1">ارفع صورة المنتج</p>
                                        <p className="text-white/30 text-xs">JPG · PNG · WEBP</p>
                                    </>
                                )}
                            </div>
                        </div>

                        {/* Optional Text Inputs (2-col grid) */}
                        <div className="grid md:grid-cols-2 gap-5">
                            {/* Product Name */}
                            <div>
                                <p className={lbl}><Wrench size={13} className="text-pink-400" />اسم المنتج</p>
                                <input
                                    type="text"
                                    value={productName}
                                    onChange={e => setProductName(e.target.value)}
                                    placeholder="اختياري - مثلاً: سيروم فيتامين سي"
                                    className={inp}
                                />
                            </div>

                            {/* Ingredients */}
                            <div>
                                <p className={lbl}><List size={13} className="text-pink-400" />المكونات</p>
                                <input
                                    type="text"
                                    value={ingredients}
                                    onChange={e => setIngredients(e.target.value)}
                                    placeholder="اختياري - مثلاً: فيتامين سي، هيالورونيك..."
                                    className={inp}
                                />
                            </div>

                            {/* Benefits / Usage */}
                            <div>
                                <p className={lbl}><Heart size={13} className="text-pink-400" />الفوائد / طريقة الاستخدام</p>
                                <input
                                    type="text"
                                    value={benefits}
                                    onChange={e => setBenefits(e.target.value)}
                                    placeholder="اختياري - مثلاً: يوضع قبل النوم..."
                                    className={inp}
                                />
                            </div>

                            {/* Dimensions — DROPDOWN */}
                            <div>
                                <p className={lbl}><Maximize size={13} className="text-pink-400" />المقاس المطلوب (Aspect Ratio)</p>
                                <select
                                    value={dimensions}
                                    onChange={e => setDimensions(e.target.value)}
                                    className={inp + ' cursor-pointer'}
                                >
                                    <option value="">تلقائي (استنتاج من الصورة)</option>
                                    <option value="21:9">21:9 — ملصق أسطواني عريض (زجاجات)</option>
                                    <option value="3:1">3:1 — ملصق شريطي طويل (برطمانات)</option>
                                    <option value="1:1">1:1 — ملصق مربع أو دائري (أغطية)</option>
                                    <option value="3:4">3:4 — ملصق عمودي (واجهة صناديق)</option>
                                </select>
                            </div>
                        </div>

                        {/* Generate Button */}
                        <button
                            onClick={handleGenerate}
                            disabled={!images.length || isGenerating}
                            className="w-full py-4 bg-gradient-to-l from-pink-700 to-pink-500 hover:from-pink-600 hover:to-pink-400 disabled:from-slate-700 disabled:to-slate-700 disabled:cursor-not-allowed rounded-2xl font-extrabold text-white flex items-center justify-center gap-3 text-sm transition-all shadow-[0_4px_20px_rgba(236,72,153,0.3)]"
                        >
                            {isGenerating
                                ? <><span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" /> جاري التوليد...</>
                                : <><Tag size={18} /> توليد برومبت الملصق</>
                            }
                        </button>

                        {/* Inline Loading Indicator */}
                        {currentStep === 'loading' && (
                            <div className="mt-6 bg-slate-900/50 border-dashed border-2 border-slate-700 rounded-2xl overflow-hidden">
                                <div className="bg-pink-600/20 py-2 px-4 flex items-center justify-center gap-2 border-b border-pink-500/20">
                                    <span className="text-pink-400 text-sm font-bold">⏳ جاري التحليل والتوليد...</span>
                                </div>
                                <div className="p-8 flex flex-col items-center text-center">
                                    <div className="w-12 h-12 border-4 border-slate-700 border-t-pink-500 rounded-full animate-spin mb-4"></div>
                                    <p className="text-slate-300 text-sm mb-3">نقوم بتحليل الصورة وتكوين البيانات المفقودة لبرومبت التصميم النانوبي...</p>
                                    <p className="text-red-500 text-xs font-bold animate-pulse">⏳ يرجى الانتظار {countdown} ثوان</p>
                                </div>
                            </div>
                        )}

                        {/* Reset Button */}
                        <button
                            onClick={handleReset}
                            className="w-full py-3 bg-white/5 hover:bg-white/10 border border-white/10 rounded-2xl font-bold text-white/70 flex items-center justify-center gap-2 text-xs transition-all"
                        >
                            <Zap size={14} /> تفريغ الحقول
                        </button>
                    </div>
                </div>

                {/* ── Results: 2-Column Grid ── */}
                {(arabicAnalysis || designPrompt) && !isGenerating && (
                    <div id="label-prompt-result" className="grid grid-cols-1 lg:grid-cols-2 gap-6 items-start mt-8">

                        {/* ─ Column 1: Arabic Analysis (Edit/Save Toggle) ─ */}
                        <div className={card + ' border-slate-700 flex flex-col'}>
                            {/* Header Row */}
                            <div className="flex items-center justify-between mb-4">
                                <h3 className="font-bold flex items-center gap-2 text-sm text-blue-300">
                                    <Info size={16} className="text-blue-400" />
                                    مخرجات التحليل والنصوص العربية
                                </h3>
                                <div className="flex items-center gap-2">
                                    {isEditing ? (
                                        <button
                                            onClick={handleSave}
                                            className="flex items-center gap-1.5 bg-purple-600 hover:bg-purple-500 text-white px-3 py-1.5 rounded-xl text-xs font-bold transition-all shadow-lg shadow-purple-500/30"
                                        >
                                            <Save size={12} /> حفظ ✅
                                        </button>
                                    ) : (
                                        <button
                                            onClick={handleEdit}
                                            className="flex items-center gap-1.5 bg-blue-600 hover:bg-blue-500 text-white px-3 py-1.5 rounded-xl text-xs font-bold transition-all shadow-lg shadow-blue-500/20"
                                        >
                                            <Edit3 size={12} /> تعديل ✏️
                                        </button>
                                    )}
                                    <button
                                        onClick={handleCopyAnalysis}
                                        className="flex items-center gap-1.5 bg-slate-800 hover:bg-slate-700 border border-slate-600 text-slate-300 px-3 py-1.5 rounded-xl text-xs font-bold transition-all"
                                    >
                                        {copiedAnalysis ? <><Check size={12} className="text-green-400" /> تم النسخ</> : <><Copy size={12} /> نسخ</>}
                                    </button>
                                </div>
                            </div>

                            {/* View Mode */}
                            {!isEditing && (
                                <div
                                    className="w-full h-[450px] overflow-y-auto bg-gray-800/50 text-white border border-slate-700/50 rounded-lg p-5 text-sm whitespace-pre-wrap leading-relaxed"
                                    dir="rtl"
                                >
                                    {arabicAnalysis}
                                </div>
                            )}

                            {/* Edit Mode */}
                            {isEditing && (
                                <textarea
                                    value={editedAnalysis}
                                    onChange={e => setEditedAnalysis(e.target.value)}
                                    className="w-full h-[450px] bg-gray-800 text-white border-2 border-purple-500/60 rounded-lg p-5 text-sm outline-none focus:border-purple-400 focus:ring-4 focus:ring-purple-500/20 transition-all resize-none leading-relaxed"
                                    dir="rtl"
                                />
                            )}
                        </div>

                        {/* ─ Column 2: Design Prompt (Read-only) ─ */}
                        <div className={card + ' border-pink-500/30 bg-pink-500/5 flex flex-col'}>
                            {/* Header Row */}
                            <div className="flex items-center justify-between mb-4">
                                <h3 className="font-bold flex items-center gap-2 text-sm text-pink-300">
                                    <Tag size={16} className="text-pink-400" />
                                    برومبت التصميم الجاهز (انسخ وضعه في الأداة 🎨)
                                </h3>
                                <button
                                    onClick={handleCopyDesign}
                                    className="flex items-center gap-1.5 bg-pink-500/20 hover:bg-pink-500/30 border border-pink-500/40 text-pink-300 px-3 py-1.5 rounded-xl text-xs font-bold transition-all"
                                >
                                    {copiedDesign ? <><Check size={12} className="text-green-400" /> تم النسخ</> : <><Copy size={12} /> نسخ</>}
                                </button>
                            </div>

                            {/* Code Block */}
                            <div
                                className="w-full h-[450px] overflow-y-auto bg-[#0d1117] border border-white/10 rounded-lg p-5 text-sm text-green-400 leading-relaxed font-mono whitespace-pre-wrap"
                                dir="ltr"
                            >
                                {designPrompt}
                            </div>
                        </div>

                    </div>
                )}

            </div>
        </div>
    );
}
