import React, { useState, useRef } from 'react';
import {
    Upload, Sparkles, Copy, Check, Info, Star, Zap,
    Target, Wrench, Wand2, Image as ImageIcon, Share2
} from 'lucide-react';
import { generateContent, radicalSanitize } from './aiService';
import { parseApiError } from './utils/errorParser';

const PLATFORMS = [
    { value: 'Instagram',  label: 'انستجرام', ratio: '1:1'  },
    { value: 'Facebook',   label: 'فيسبوك',   ratio: '4:5'  },
    { value: 'TikTok',     label: 'تيك توك',  ratio: '9:16' },
];

export default function SocialPromptTool() {
    const [images, setImages]           = useState([]);
    const [productName, setProductName] = useState('');
    const [offer, setOffer]             = useState('');
    const [hasDiscount, setHasDiscount] = useState(false);
    const [currentPrice, setCurrentPrice] = useState('');
    const [originalPrice, setOriginalPrice] = useState('');
    const [discountedPrice, setDiscountedPrice] = useState('');
    const [currency, setCurrency] = useState('دولار $');
    const [contact, setContact] = useState('');
    const [angle, setAngle]             = useState('مشكلة وحل');
    const [platform, setPlatform]       = useState('Instagram');
    const [language, setLanguage]       = useState('Arabic');
    const [outputStyle, setOutputStyle] = useState('Realistic');
    const [isGenerating, setIsGenerating] = useState(false);
    const [currentStep, setCurrentStep]   = useState('idle'); // 'idle' | 'loading' | 'success'
    const [countdown, setCountdown]       = useState(30);
    const [result, setResult]             = useState('');
    const [designPrompt, setDesignPrompt] = useState('');
    const [copiedDesign, setCopiedDesign] = useState(false);
    const [error, setError]               = useState('');
    const fileRef = useRef(null);

    const currentPlatform = PLATFORMS.find(p => p.value === platform);

    const handleFiles = async (e) => {
        const files = Array.from(e.target.files || []);
        if (!files.length) return;
        const slots = 4 - images.length;
        const b64s = await Promise.all(
            files.slice(0, slots).map(f => new Promise(res => {
                const r = new FileReader();
                r.onloadend = () => res(r.result);
                r.readAsDataURL(f);
            }))
        );
        setImages(prev => [...prev, ...b64s]);
        e.target.value = '';
    };

    const removeImg = i => setImages(prev => prev.filter((_, idx) => idx !== i));

    const getCurrencies = (lang) => {
        const l = lang.toLowerCase();
        if (l === 'english') return ['Dollar $', 'Riyal', 'Dirham', 'Pound', 'Dinar', 'Euro €'];
        if (l === 'french') return ['Dollar $', 'Riyal', 'Dirham', 'Livre', 'Dinar', 'Euro €'];
        if (l === 'spanish') return ['Dólar $', 'Riyal', 'Dirham', 'Libra', 'Dinar', 'Euro €'];
        return ['دولار $', 'ريال', 'درهم', 'جنيه', 'دينار', 'يورو €'];
    };

    const getUIText = (lang) => {
        const l = lang.toLowerCase();
        const texts = {
            arabic: { pricing: 'التسعير والعروض (اختياري)', hasDiscount: 'يوجد خصم', price: 'السعر الحالي', original: 'السعر الأصلي', discount: 'السعر بعد الخصم', currency: 'العملة', placeholder: 'مثال: 99' },
            english: { pricing: 'Pricing & Offers (Optional)', hasDiscount: 'Has Discount', price: 'Current Price', original: 'Original Price', discount: 'Discounted Price', currency: 'Currency', placeholder: 'e.g. 99' },
            french: { pricing: 'Prix et Offres (Optionnel)', hasDiscount: 'Avec Remise', price: 'Prix Actuel', original: 'Prix Original', discount: 'Prix avec Remise', currency: 'Devise', placeholder: 'ex: 99' },
            spanish: { pricing: 'Precios y Ofertas (Opcional)', hasDiscount: 'Con Descuento', price: 'Precio Actual', original: 'Precio Original', discount: 'Precio de Descuento', currency: 'Moneda', placeholder: 'ej: 99' }
        };
        return texts[l] || texts.arabic;
    };

    const systemPrompt = `Act as a world-class Arabic Direct Response Copywriter and AI Prompt Engineer specializing in image-based mobile-first Social Media Ads generated by 'Nano Banana Pro'.

Analyze the uploaded product image. Identify the product, its key features, target audience, and best color palette. 

### YOUR MISSION HAS TWO CRITICAL STEPS:

### STEP 1: TEXT GENERATION (COPYWRITING)
First, write highly persuasive, punchy Arabic sales copy for a social media ad based on the product. Present this copy clearly in your response so I can read it, review it, and use it.

### STEP 2: NANO BANANA PRO DESIGN PROMPT
After presenting the copywriting, output a single, consolidated READY-TO-COPY design prompt for the "Nano Banana Pro" image generator.

---
### CRITICAL INSTRUCTIONS FOR STEP 2 OUTPUT:
1. Output Format: Provide the entire design prompt inside a single code block.
2. Product Context: Explicitly describe the product visually in the prompt. 
3. Visual Descriptions: Add strong, creative English visual descriptions based on the uploaded image.
4. Typography Integration: You MUST take the Arabic text you generated in STEP 1, and insert it directly into the Step 2 prompt replacing the [bracketed placeholders]. 
5. The Arabic text must be placed EXACTLY inside quotation marks " ".
6. DO NOT render any English structural labels (like Headline, Body Text) inside the final prompt. Just the visual descriptions and the Arabic text in quotes.`;

    const handleGenerate = async () => {
        if (!images.length) { setError('يرجى رفع صورة المنتج أولاً.'); return; }
        setError('');
        setResult('');
        setDesignPrompt('');
        setIsGenerating(true);
        setCurrentStep('loading');
        setCountdown(30);

        const startTime = Date.now();
        const timer = setInterval(() => {
            setCountdown(prev => (prev <= 1 ? 0 : prev - 1));
        }, 1000);

        const ratio = currentPlatform.ratio;
        const pName = radicalSanitize(productName.trim() !== '' ? productName : 'استنتج اسم المنتج من الصورة');

        let pricingContext = '';
        if (hasDiscount && originalPrice && discountedPrice) {
            pricingContext = `Offer: Original ${originalPrice} ${currency}, Now ${discountedPrice} ${currency}. Highlight scarcity!`;
        } else if (currentPrice) {
            pricingContext = `Price: ${currentPrice} ${currency}.`;
        }
        
        const internalPrompt = `--- USE THIS EXACT TEMPLATE FOR STEP 2 (DESIGN PROMPT) ---

Act as a world-class Social Media Ad Designer. Generate a high-resolution, scroll-stopping Social Media Ad IMAGE (aspect ratio ${ratio}) for the [Describe the product visually here] in the uploaded image.

CRITICAL FORMAT RULE: DO NOT write any HTML, CSS, UI code, or text-based code. You MUST generate a purely visual, single continuous graphical IMAGE.

AESTHETIC & FLOW INSTRUCTIONS:
Create a highly engaging visual composition with smooth color gradients (specifically [insert dynamic colors matching product image]). The layout must be clean and impactful, optimized for social media feeds.

* Dynamic, premium background matching the product vibe. Small glowing badge in the corner: "[Insert Short Arabic text: الأكثر مبيعاً or جديد]"
* HUGE WHITE BOLD TEXT (Top or Center-Top): "[Insert Arabic Main Hook/Headline]"
* The Product is featured prominently, large scale, with cinematic lighting and subtle glowing or particle effects to make it pop.
* Medium Bold Text (floating near the product): "[Insert Arabic Main Benefit/Solution]"
* Visual proof element: A small split or visual cue showing [describe problem] vs [describe happy state]. LARGE BOLD COLORED TEXT: "[Insert short Arabic text about the transformation]"
* Solid, high-contrast lower section. 
* HUGE BLACK TEXT on a glowing YELLOW Button graphic: "اطلب الآن - الدفع عند الاستلام"

\`\`\`text
[Insert Nano Banana Pro English Prompt Here with Arabic text in quotes]
\`\`\``;

        try {
            const outputText = await generateContent({
                systemPrompt,
                userPrompt: internalPrompt,
                imageBase64: images[0]
            });
            const cleanPrompt = outputText.replace(/```[a-zA-Z]*\n?/g, '').replace(/```$/g, '').trim();
            setDesignPrompt(cleanPrompt);
            setResult(outputText);

            const elapsed = Date.now() - startTime;
            const remaining = Math.max(0, 30000 - elapsed);
            if (remaining > 0) await new Promise(res => setTimeout(res, remaining));

            setCurrentStep('success');
            setTimeout(() => document.getElementById('social-result')?.scrollIntoView({ behavior: 'smooth' }), 100);
        } catch (err) {
            const userFriendlyMsg = parseApiError(err);
            setError(userFriendlyMsg);
            setCurrentStep('idle');
        } finally {
            setIsGenerating(false);
            clearInterval(timer);
        }
    };

    const handleCopyDesign = () => {
        navigator.clipboard.writeText(designPrompt);
        setCopiedDesign(true);
        setTimeout(() => setCopiedDesign(false), 2000);
    };

    const handleReset = () => {
        setImages([]);
        setProductName('');
        setOffer('');
        setHasDiscount(false);
        setCurrentPrice('');
        setOriginalPrice('');
        setDiscountedPrice('');
        setCurrency('دولار $');
        setContact('');
        setAngle('مشكلة وحل');
        setPlatform('Instagram');
        setLanguage('Arabic');
        setOutputStyle('Realistic');
        setResult('');
        setDesignPrompt('');
        setCopiedDesign(false);
        setError('');
        if (fileRef.current) fileRef.current.value = '';
    };

    const card = 'bg-slate-900/70 border border-white/10 rounded-3xl p-7 backdrop-blur-sm';
    const sel  = 'w-full bg-slate-950 border border-white/10 rounded-xl p-4 text-white text-sm outline-none focus:border-purple-500 transition-all appearance-none';
    const lbl  = 'flex items-center gap-2 text-xs font-bold text-white/60 mb-2';
    const inp  = 'w-full bg-slate-950 border border-white/10 rounded-xl p-3 text-white text-sm outline-none focus:border-purple-500 transition-all placeholder:text-white/20';

    return (
        <div className="h-full overflow-y-auto text-slate-100" dir="rtl" style={{ scrollbarWidth: 'none' }}>
            <div className="max-w-6xl mx-auto px-4 md:px-10 py-10">
                <div className="text-center mb-12">
                    <div className="inline-flex items-center gap-2 bg-purple-500/10 border border-purple-500/20 text-purple-400 text-xs font-bold px-4 py-1.5 rounded-full mb-5">
                        <Share2 size={13} /> Nano Banana Pro
                    </div>
                    <h1 className="text-4xl md:text-5xl font-black mb-3 leading-tight">
                        برومبت السوشيال ميديا
                        <span className="block text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-fuchsia-400 text-2xl md:text-3xl mt-2">
                            انستجرام 1:1 · فيسبوك 4:5 · تيك توك 9:16
                        </span>
                    </h1>
                    <p className="text-white/40 text-sm max-w-lg mx-auto leading-relaxed">
                        أدخل بيانات منتجك واحصل على نصوص إعلانية وبرومبت جاهز للنسخ في Nano Banana Pro
                    </p>
                </div>

                {error && (
                    <div className="mb-6 bg-red-500/10 border border-red-500/30 text-red-400 px-5 py-3 rounded-2xl text-sm">⚠️ {error}</div>
                )}

                <div className="grid lg:grid-cols-12 gap-8">
                    <div className="lg:col-span-8 space-y-6">
                        <div className={card + ' space-y-7'}>
                            <div>
                                <p className={lbl}><ImageIcon size={13} className="text-purple-400" />صورة المنتج (مطلوبة)</p>
                                <div
                                    onClick={() => images.length < 4 && fileRef.current?.click()}
                                    className={`border-2 border-dashed rounded-2xl p-5 cursor-pointer transition-all flex flex-col items-center justify-center min-h-[180px]
                                        ${images.length ? 'border-purple-500/40 bg-purple-500/5' : 'border-white/10 hover:border-purple-500/40 bg-white/5'}
                                        ${images.length >= 4 ? 'opacity-50 cursor-not-allowed' : ''}`}
                                >
                                    <input type="file" ref={fileRef} onChange={handleFiles} accept="image/*" multiple className="hidden" />
                                    {images.length ? (
                                        <div className="w-full">
                                            <div className="grid grid-cols-4 gap-3">
                                                {images.map((img, i) => (
                                                    <div key={i} className="relative aspect-square">
                                                        <img src={img} className="w-full h-full object-cover rounded-xl border border-white/10" alt="" />
                                                        <button onClick={e => { e.stopPropagation(); removeImg(i); }} className="absolute -top-1.5 -right-1.5 bg-red-500 text-white w-5 h-5 rounded-full text-xs flex items-center justify-center z-10">✕</button>
                                                    </div>
                                                ))}
                                            </div>
                                        </div>
                                    ) : (
                                        <>
                                            <div className="w-14 h-14 bg-purple-500/15 rounded-full flex items-center justify-center mb-3">
                                                <Upload size={26} className="text-purple-400" />
                                            </div>
                                            <p className="font-bold text-base mb-1">ارفع صورة المنتج</p>
                                            <p className="text-white/30 text-xs">JPG · PNG · WEBP (حتى 4 صور)</p>
                                        </>
                                    )}
                                </div>
                            </div>

                            <div>
                                <p className={lbl}><Target size={13} className="text-purple-400" />المنصة الإعلانية</p>
                                <div className="grid grid-cols-3 gap-3">
                                    {PLATFORMS.map(p => (
                                        <button
                                            key={p.value}
                                            onClick={() => setPlatform(p.value)}
                                            className={`py-4 rounded-2xl border text-center transition-all ${platform === p.value
                                                ? 'bg-purple-500/15 border-purple-500 text-purple-200'
                                                : 'bg-white/5 border-white/10 text-white/40 hover:border-white/20'}`}
                                        >
                                            <p className="font-extrabold text-sm">{p.label}</p>
                                            <p className="text-[10px] mt-1 opacity-60">{p.ratio}</p>
                                        </button>
                                    ))}
                                </div>
                            </div>

                            <div className="grid md:grid-cols-2 gap-5">
                                <div>
                                    <p className={lbl}><Wrench size={13} className="text-purple-400" />اسم المنتج</p>
                                    <input type="text" value={productName} onChange={e => setProductName(e.target.value)} placeholder="مثال: كريم العناية بالبشرة" className={inp} />
                                </div>
                                <div>
                                    <p className={lbl}><Zap size={13} className="text-purple-400" />الزاوية التسويقية</p>
                                    <select value={angle} onChange={e => setAngle(e.target.value)} className={sel}>
                                        <option>مشكلة وحل</option>
                                        <option>استجابة مباشرة</option>
                                        <option>دليل اجتماعي</option>
                                        <option>عرض محدود بوقت</option>
                                        <option>فائدة وظيفية</option>
                                    </select>
                                </div>
                                <div>
                                    <p className={lbl}><Share2 size={13} className="text-purple-400" />لغة المحتوى</p>
                                    <select value={language} onChange={e => setLanguage(e.target.value)} className={sel}>
                                        <option value="Arabic">العربية (الأسواق المحلية والخليج)</option>
                                        <option value="English">الإنجليزية (الأسواق العالمية والدروبشيبينغ)</option>
                                        <option value="French">الفرنسية (أسواق أفريقيا وأوروبا)</option>
                                        <option value="Spanish">الإسبانية (أمريكا اللاتينية وإسبانيا)</option>
                                    </select>
                                </div>
                                <div>
                                    <p className={lbl}><Wand2 size={13} className="text-purple-400" />نمط الإخراج</p>
                                    <select value={outputStyle} onChange={e => setOutputStyle(e.target.value)} className={sel}>
                                        <option value="Realistic">واقعي (Realistic)</option>
                                        <option value="3D Isometric">ثلاثي الأبعاد (3D Isometric)</option>
                                        <option value="Minimalist">بسيط (Minimalist)</option>
                                        <option value="Vibrant">حيوي (Vibrant)</option>
                                    </select>
                                </div>

                                <div className="md:col-span-2 bg-white/5 border border-white/10 rounded-2xl p-5 mt-2">
                                    <div className="flex items-center justify-between mb-4">
                                        <p className="text-xs font-bold text-purple-400 flex items-center gap-2">
                                            <Sparkles size={13} /> {getUIText(language).pricing}
                                        </p>
                                        <label className="relative inline-flex items-center cursor-pointer">
                                            <input type="checkbox" className="sr-only peer" checked={hasDiscount} onChange={() => setHasDiscount(!hasDiscount)} />
                                            <div className="w-10 h-5 bg-white/10 peer-focus:outline-none rounded-full peer peer-checked:after:-translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:right-[2px] after:bg-white/40 after:border-white/10 after:border after:rounded-full after:h-4 after:w-4 after:transition-all peer-checked:bg-purple-600"></div>
                                            <span className="mr-3 text-[10px] font-medium text-white/40">{getUIText(language).hasDiscount}</span>
                                        </label>
                                    </div>
                                    <div className="grid md:grid-cols-2 gap-4">
                                        {!hasDiscount ? (
                                            <div className="col-span-full flex gap-3">
                                                <div className="flex-1">
                                                    <input type="number" value={currentPrice} onChange={e => setCurrentPrice(e.target.value)} placeholder={getUIText(language).price} className={inp} />
                                                </div>
                                                <div className="w-24">
                                                    <select value={currency} onChange={e => setCurrency(e.target.value)} className={sel}>
                                                        {getCurrencies(language).map(c => <option key={c} value={c}>{c}</option>)}
                                                    </select>
                                                </div>
                                            </div>
                                        ) : (
                                            <>
                                                <input type="number" value={originalPrice} onChange={e => setOriginalPrice(e.target.value)} placeholder={getUIText(language).original} className={inp} />
                                                <div className="flex gap-3">
                                                    <input type="number" value={discountedPrice} onChange={e => setDiscountedPrice(e.target.value)} placeholder={getUIText(language).discount} className={inp} />
                                                    <select value={currency} onChange={e => setCurrency(e.target.value)} className={sel}>
                                                        {getCurrencies(language).map(c => <option key={c} value={c}>{c}</option>)}
                                                    </select>
                                                </div>
                                            </>
                                        )}
                                    </div>
                                </div>
                            </div>

                            <button
                                onClick={handleGenerate}
                                disabled={!images.length || isGenerating}
                                className="w-full py-4 bg-gradient-to-l from-purple-700 to-purple-500 hover:from-purple-600 hover:to-purple-400 disabled:from-slate-700 disabled:to-slate-700 disabled:cursor-not-allowed rounded-2xl font-extrabold text-white flex items-center justify-center gap-3 text-sm transition-all shadow-[0_4px_20px_rgba(168,85,247,0.3)]"
                            >
                                {isGenerating ? <><span className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" /> جاري التوليد...</> : <><Sparkles size={18} /> توليد الإعلان الاحترافي</>}
                            </button>
                            
                            {/* Stage 2: Inline Loading State */}
                            {currentStep === 'loading' && (
                                <div className="mt-6 bg-slate-900/50 border-dashed border-2 border-slate-700 rounded-2xl overflow-hidden animate-slide-down">
                                    {/* Blue header */}
                                    <div className="bg-blue-600/20 py-2 px-4 flex items-center justify-center gap-2 border-b border-blue-500/20">
                                        <span className="text-blue-400 text-sm font-bold">⏳ جاري التوليد...</span>
                                    </div>

                                    <div className="p-8 flex flex-col items-center text-center">
                                        {/* Spinner */}
                                        <div className="w-12 h-12 border-4 border-slate-700 border-t-blue-500 rounded-full animate-spin mb-4"></div>
                                        <p className="text-slate-300 text-sm mb-3">جاري تجهيز البرومبت المزود بالذكاء الاصطناعي...</p>
                                        <p className="text-red-500 text-xs font-bold animate-pulse">⏳ يرجى الانتظار {countdown} ثوان</p>
                                    </div>
                                </div>
                            )}

                            <button onClick={handleReset} className="w-full py-3 bg-white/5 hover:bg-white/10 border border-white/10 rounded-2xl font-bold text-white/70 flex items-center justify-center gap-2 text-xs transition-all">
                                <Zap size={14} /> تفريغ الحقول
                            </button>
                        </div>

                        {designPrompt && (
                            <div id="social-result" className={card + ' space-y-4 animate-in fade-in duration-500 border border-purple-500/20 bg-purple-500/5'}>
                                <div className="flex items-center justify-between">
                                    <h3 className="font-bold flex items-center gap-2 text-sm text-purple-300">
                                        <Check size={16} className="text-purple-400" /> برومبت التصميم الجاهز (Ready Prompt)
                                    </h3>
                                    <button onClick={handleCopyDesign} className="flex items-center gap-2 bg-purple-500/15 hover:bg-purple-500/25 border border-purple-500/30 text-purple-300 px-4 py-2 rounded-xl text-xs font-bold transition-all">
                                        {copiedDesign ? <><Check size={12} className="text-green-400" /> تم النسخ</> : <><Copy size={12} /> نسخ البرومبت</>}
                                    </button>
                                </div>
                                <div className="bg-black/50 rounded-2xl p-5 text-xs text-white/85 leading-relaxed border border-white/5 whitespace-pre-wrap font-mono" dir="ltr">
                                    {designPrompt}
                                </div>
                            </div>
                        )}
                    </div>

                    <div className="lg:col-span-4 space-y-5">
                        <div className={card + ' space-y-4'}>
                            <div className="flex items-center gap-2 text-purple-400">
                                <Info size={15} /><h3 className="font-bold text-sm">كيف تستخدم البرومبت؟</h3>
                            </div>
                            {[
                                'ارفع صورة المنتج واختر المنصة المستهدفة.',
                                'أضف اسم المنتج والزاوية التسويقية.',
                                'اضغط على زر "توليد" للحصول على البرومبت.',
                                'انسخ برومبت التصميم واستخدمه في Nano Banana Pro.'
                            ].map((t, i) => (
                                <div key={i} className="flex gap-3 text-xs text-white/60 bg-black/20 p-3 rounded-xl border border-white/5">
                                    <span className="flex-shrink-0 w-5 h-5 bg-purple-500/20 rounded-full flex items-center justify-center text-[10px] font-bold text-purple-400">{i + 1}</span>
                                    <p className="leading-relaxed">{t}</p>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}